### Get all tweets
GET http://localhost:8080/api/tweets

### Create a tweet
POST http://localhost:8080/api/tweets
Content-Type: application/json

{
    "id": "6092a031a8452925eaa86ac3",
    "body": "Hello, this is my first tweet!"
}

### Reply to a tweet
POST http://localhost:8080/api/tweets/reply/6092d94ceb4d8e40de5414e2
Content-Type: application/json

{
    "id": "6092a031a8452925eaa86ac3",
    "body": "I can't believe it!"
}

### Get all replies to a tweet
GET http://localhost:8080/api/tweets/replies/6092d94ceb4d8e40de5414e2

### Get tweet that is replied to
GET http://localhost:8080/api/tweets/replyto/60941e671cd5810d0a2ec40e