### Get all users
GET http://localhost:8080/api/users

### Create a new user in the database
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "Chickies",
    "email": "lindsaymarycayas@gmail.com",
    "password": "chickies"
}

### Delete a user
DELETE http://localhost:8080/api/users/id/60929c3e7e6c3123f035383e

### Follow another user
PATCH http://localhost:8080/api/users/follow/6092a01fa8452925eaa86ac2
Content-Type: application/json

{
    "id": "6092a031a8452925eaa86ac3"
}

### Unfollow another user
PATCH http://localhost:8080/api/users/unfollow/6092a01fa8452925eaa86ac2
Content-Type: application/json

{
    "id": "6092a031a8452925eaa86ac3"
}

### Clear follows
PATCH http://localhost:8080/api/users/follow
